### ISSUE TITLE
How to send a PM?

### ISSUE THREAD

**Issue by ghost** [qeled/discordie#112]

**Comment by Senither** [comment]
You could always check the [docs](https://qeled.github.io/discordie/#/?_k=d5werz) for how to do it, but since you took the time to create a issue on github, you can use the [openDM](https://qeled.github.io/discordie/#/docs/IGuildMember?p=IGuildMember%23openDM) method on the [IUser](https://qeled.github.io/discordie/#/docs/IUser?_k=pfuxob) or [IGuildMember](https://qeled.github.io/discordie/#/docs/IGuildMember?_k=ph4nm9) objects.
