### ISSUE TITLE
library not ES6 compliant

### ISSUE THREAD

**Issue by neico** [qeled/discordie#22]
When I tried to use this lib with NodeJS 6.3.x and `--harmony` it resulted in strange errors in collections. (without the flag it works fine)
After looking through the code a bit it's become clear that this library is using quite old, deprecated things that most likely won't work in NodeJS 7.0.0 and upwards (as 7.0.0 will likely be 100% ES6 compliant since it's already at 99%).

One of those deprecated features is __proto__ where you can simply use Object.getPrototypeOf() by now.

If you want to keep compatibility with older versions at least make a new branch and push that to "next" or so on npm.

**Comment by qeled** [comment]
Indeed, constructor was being called multiple times due to a recent ES2015 compliancy change in V8 engine. Fixed with https://github.com/qeled/discordie/commit/58f6e743e68da80eabcd7831f59f49b86fd0f089.

As for `__proto__` (though it isn't related to the crash), it is indeed deprecated and I've replaced it, but still it will not be removed from V8, that would break a lot of old code. It has been standardized as [part of ES6](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) and marked as legacy.

Currently the changes above are in the [dev branch](https://github.com/qeled/discordie/commits/dev).

**Comment by qeled** [comment]
Fixed in version 0.7.5.
