### ISSUE TITLE
Permission recommendation

### ISSUE THREAD

**Issue by Ryu945** [qeled/discordie#26]
To get a guild permission is something like this:
``e.message.author.can(Discordie.Permissions.Text.MANAGE_MESSAGES, e.message.guild)``

To get a channel permission is something like this:

```
try{
		var channel_permission = guild.generalChannel.permission_overwrites.filter(roleperm=> roleperm.id == e.message.author.memberOf(e.message.guild).roles[0].id)[0].allow.Text.MANAGE_MESSAGES;
} catch (err) {
	var channel_permission = guild.generalChannel.permission_overwrites.filter(roleperm=> roleperm.id == e.message.guild.id)[0].allow.Text.MANAGE_MESSAGES;
}
e.message.author.can(channel_permission,guild)
```

With that it is true for given and false for neutral or denied.

```
try{
		var channel_permission = !guild.generalChannel.permission_overwrites.filter(roleperm=> roleperm.id == e.message.author.memberOf(e.message.guild).roles[0].id)[0]deny.Text.MANAGE_MESSAGES;
} catch (err) {
	var channel_permission = !guild.generalChannel.permission_overwrites.filter(roleperm=> roleperm.id == e.message.guild.id)[0].deny.Text.MANAGE_MESSAGES;
}
e.message.author.can(channel_permission,guild)
```

This on the other had is true for allowed and neutral while false for denied.

I noticed with this:

``e.message.author.can(Discordie.Permissions.Text.MANAGE_MESSAGES, e.message.channel)``

It pulls the channels permissions instead.  It is a true for allowed while false for neutral and denied.  This is far simpler way of checking channel permission but what would be nice is if there is a way to use the deny like was used above so that allowed and neutral are true and denied is false.

**Comment by qeled** [comment]
Getters in your first 2 snippets return booleans, not permission bits. Those are meant to get and set permissions by directly assigning values to them, and then submit them to Discord. Passing booleans into the `.can` method will not return useful data since it will only check the first bit of the permission bitfield.

Resulting permissions are computed from `allow`, `deny` and default permissions. What you suggest will end up returning invalid permissions, since neutral is true if default for that permission is true, but a `deny` bit higher up the hierarchy can make this false.
